export const products = [
  {
    id: 1246,
    name: 'PLACA DE VIDEO GIGABYTE GEFORCE RTX 4060 EAGLE OC, 8GB, GDDR6, 128-BIT, GV-N4060EAGLE-OC-8GD',
    brand: 'Gigabyte',
    image: [
      '/assets/imgProducts/placa-de-video-rtx-4060-ti-gigabyte1.jpg',
      '/assets/imgProducts/placa-de-video-rtx-4060-ti-gigabyte3.jpg',
      '/assets/imgProducts/placa-de-video-rtx-4060-ti-gigabyte2.jpg',
    ],
    rating: 4.5,
    amount_rating: 15,
    brand_id: 3,
    category_id: 4596,
    warranty: 24,
    seller_id: 1,
    value: {
      priceNow: 2249.99,
      CommonPrice: 3000.0,
      portions: 12,
      feesMonthly: 1.5,
      feesCredit: 4,
    },
  },
  {
    id: 1895,
    name: 'MacBook Pro 14" Apple M2 Pro (16GB RAM 512GB SSD) Cinza Espacial',
    brand: 'Apple',
    image: [
      '/assets/imgProducts/macbook_pro_m2_pro_1.jpeg',
      '/assets/imgProducts/macbook_pro_m2_pro_2.jpeg',
      '/assets/imgProducts/macbook_pro_m2_pro_3.jpeg',
      '/assets/imgProducts/macbook_pro_m2_pro_4.jpeg',
      '/assets/imgProducts/macbook_pro_m2_pro_5.jpeg',
      '/assets/imgProducts/macbook_pro_m2_pro_6.jpeg',
    ],
    rating: 4.8,
    amount_rating: 30,
    brand_id: 1,
    category_id: 2486,
    warranty: 12,
    seller_id: 1,
    value: {
      priceNow: 18499.99,
      CommonPrice: 24999.99,
      portions: 12,
      feesMonthly: 1.6,
      feesCredit: 4,
    },
  },
  {
    id: 1818,
    name: 'iPhone 15 Apple (128GB) Verde, Tela de 6,1", 5G e Câmera de 48 MP',
    brand: 'Apple',
    image: [
      '/assets/imgProducts/iphone15_1.jpeg',
      '/assets/imgProducts/iphone15_3.jpeg',
      '/assets/imgProducts/iphone15_4.jpeg',
      '/assets/imgProducts/iphone15_5.jpeg',
      '/assets/imgProducts/iphone15_6.jpeg',
    ],
    rating: 4.8,
    amount_rating: 30,
    brand_id: 1,
    category_id: 2486,
    warranty: 12,
    seller_id: 1,
    value: {
      priceNow: 10499.99,
      CommonPrice: 10999.99,
      portions: 12,
      feesMonthly: 1.4,
      feesCredit: 3,
    },
  },
  {
    id: 1851,
    name: 'iPhone 15 Pro Apple (512GB) Titânio Natural, Tela de 6,1", 5G e Câmera de 48MP',
    brand: 'Apple',
    image: [
      '/assets/imgProducts/iphone15pro_1.jpeg',
      '/assets/imgProducts/iphone15pro_3.jpeg',
      '/assets/imgProducts/iphone15pro_4.jpeg',
      '/assets/imgProducts/iphone15pro_5.jpeg',
      '/assets/imgProducts/iphone15pro_6.jpeg',
      '/assets/imgProducts/iphone15pro_7.jpeg',
    ],
    rating: 4.8,
    amount_rating: 30,
    brand_id: 1,
    category_id: 2486,
    warranty: 12,
    seller_id: 1,
    value: {
      priceNow: 10499.99,
      CommonPrice: 10999.99,
      portions: 12,
      feesMonthly: 1.4,
      feesCredit: 3,
    },
  },
  {
    id: 1941,
    name: 'Placa de Vídeo RTX 4090 ROG Strix Asus NVIDIA GeForce, 24 GB GDDR6X, ARGB, DLSS, Ray Tracing - ROG-STRIX-RTX4090-24G-GAMING',
    brand: 'Asus',
    image: [
      '/assets/imgProducts/rtx-4090-rog-strix-asus_1.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_2.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_3.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_4.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_5.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_6.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_7.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_8.jpeg',
      '/assets/imgProducts/rtx-4090-rog-strix-asus_9.jpeg',
    ],
    rating: 4.6,
    amount_rating: 35,
    brand_id: 2,
    category_id: 4596,
    warranty: 24,
    seller_id: 1,
    value: {
      priceNow: 11999.99,
      CommonPrice: 14999.99,
      portions: 12,
      feesMonthly: 1.3,
      feesCredit: 5,
    },
  },
  {
    id: 1942,
    name: 'Placa de Vídeo RTX 4070 TUF Gaming OC Edition Asus NVIDIA GeForce, 12 GB GDDR6X, ARGB, DLSS, Ray Tracing - TUF-RTX4070-O12G-GAMING',
    brand: 'Asus',
    image: [
      '/assets/imgProducts/rtx-4070-asus_1.jpeg',
      '/assets/imgProducts/rtx-4070-asus_2.jpeg',
      '/assets/imgProducts/rtx-4070-asus_3.jpeg',
      '/assets/imgProducts/rtx-4070-asus_4.jpeg',
      '/assets/imgProducts/rtx-4070-asus_5.jpeg',
      '/assets/imgProducts/rtx-4070-asus_6.jpeg',
    ],
    rating: 4.5,
    amount_rating: 2,
    brand_id: 2,
    category_id: 4596,
    warranty: 24,
    seller_id: 1,
    value: {
      priceNow: 4799.99,
      CommonPrice: 5299.99,
      portions: 12,
      feesMonthly: 1.45,
      feesCredit: 3,
    },
  },
];
