export const ALTER_CARRINHO = 'ALTER_CARRINHO';
export const INITIALIZE_CART = 'INITIALIZE_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_AMOUNT_PRODUCT = 'INCREMENT_AMOUNT_PRODUCT;';
export const DECREMENT_AMOUNT_PRODUCT = 'DECREMENT_AMOUNT_PRODUCT;';
